# 75 Blind 75 Problem Dataset with 6-Pillar Format (Hinglish + Layman + Diagrams + Brute/Optimal + Pitch + Production War Story)

BLIND_75_DATA = [
    # 01-Arrays & Hashing (1-8)
    {"cat": "01-arrays-and-hashing", "id": 1, "lc": 1, "title": "Two Sum", "diff": "Easy",
     "hinglish": "Budget fix hai (target). Har element dekhte waqt check karo ki (target - current_element) pehle dekha hai ya nahi.",
     "analogy": "Target bill in grocery shopping. Keep a clipboard of prices needed to reach the total.",
     "brute": "Nested loops comparing all pairs (nums[i] + nums[j] == target). Time: O(N^2), Space: O(1).",
     "optimal": "One-pass Hash Map storing number -> index. Lookup complement in O(1). Time: O(N), Space: O(N).",
     "py": "def twoSum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen: return [seen[target - n], i]\n        seen[n] = i\n    return []",
     "js": "function twoSum(nums, target) {\n    const map = new Map();\n    for (let i = 0; i < nums.length; i++) {\n        const diff = target - nums[i];\n        if (map.has(diff)) return [map.get(diff), i];\n        map.set(nums[i], i);\n    }\n    return [];\n}",
     "diagram": "[2, 7, 11, 15], Target=9\ni=0: num=2, diff=7, Map={2:0}\ni=1: num=7, diff=2, Map has 2! -> Return [0, 1]",
     "star": "Fintech ledger reconciliation engine matching unsettled credit transactions with pending invoice receipts. Replaced nested loop with hash-set lookup.",
     "metrics": "Execution time dropped from 45 minutes to 7.8 seconds for 50,000 daily transaction batches."},

    {"cat": "01-arrays-and-hashing", "id": 2, "lc": 217, "title": "Contains Duplicate", "diff": "Easy",
     "hinglish": "Check karo array me koi number 2 ya usse zyada baar aaya hai. Set use karo.",
     "analogy": "Guest list at event door. Check if person's name is already checked in on the sheet.",
     "brute": "Sort array and compare adjacent elements. Time: O(N log N), Space: O(1).",
     "optimal": "Hash Set single pass. If num in set, return True. Time: O(N), Space: O(N).",
     "py": "def containsDuplicate(nums):\n    seen = set()\n    for n in nums:\n        if n in seen: return True\n        seen.add(n)\n    return False",
     "js": "function containsDuplicate(nums) {\n    const set = new Set();\n    for (const n of nums) {\n        if (set.has(n)) return true;\n        set.add(n);\n    }\n    return false;\n}",
     "diagram": "[1, 2, 3, 1]\nSeen: {1} -> {1, 2} -> {1, 2, 3} -> 1 is already in Set! -> Return True",
     "star": "Bulk CSV importer for employee phone numbers. Deduplicated records in memory before running database transactions.",
     "metrics": "Prevented 100% of batch primary key constraint rollbacks and cut processing time from 3 mins to 4 secs."},

    {"cat": "01-arrays-and-hashing", "id": 3, "lc": 242, "title": "Valid Anagram", "diff": "Easy",
     "hinglish": "Do words anagram tab hain jab dono me exact same letters exact same frequency me hon.",
     "analogy": "Scrabble tiles: both words must be formed by rearranging the identical set of letter tiles.",
     "brute": "Sort both strings and check if sorted(s) == sorted(t). Time: O(N log N), Space: O(N).",
     "optimal": "26-length fixed frequency array. Increment for s, decrement for t. Time: O(N), Space: O(1).",
     "py": "def isAnagram(s: str, t: str) -> bool:\n    if len(s) != len(t): return False\n    count = [0] * 26\n    for a, b in zip(s, t):\n        count[ord(a) - ord('a')] += 1\n        count[ord(b) - ord('a')] -= 1\n    return all(x == 0 for x in count)",
     "js": "function isAnagram(s, t) {\n    if (s.length !== t.length) return false;\n    const freq = new Array(26).fill(0);\n    for (let i = 0; i < s.length; i++) {\n        freq[s.charCodeAt(i) - 97]++;\n        freq[t.charCodeAt(i) - 97]--;\n    }\n    return freq.every(x => x === 0);\n}",
     "diagram": "s='anagram', t='nagaram'\nFrequency counter counts all characters to 0 -> True",
     "star": "Multilingual search catalog keyword sanitizer. Matched permuted tag search queries without running heavy regex scans.",
     "metrics": "Processed 2.5 million tags with zero heap allocation overhead; dropped query latency from 45ms to 2ms."},

    {"cat": "01-arrays-and-hashing", "id": 4, "lc": 49, "title": "Group Anagrams", "diff": "Medium",
     "hinglish": "Jo words ek dusre ke anagram hain unko ek group me rakhna hai. Sorted word ya char-frequency tuple ko hashmap key banao.",
     "analogy": "Sorting library books into shelves where all books with the same character combination go to the same shelf.",
     "brute": "Compare every word pair with O(N^2) anagram checks. Time: O(N^2 * K).",
     "optimal": "HashMap with sorted string or 26-char count tuple as key. Time: O(N * K log K) or O(N * K), Space: O(N * K).",
     "py": "from collections import defaultdict\ndef groupAnagrams(strs):\n    groups = defaultdict(list)\n    for s in strs:\n        key = tuple(sorted(s))\n        groups[key].append(s)\n    return list(groups.values())",
     "js": "function groupAnagrams(strs) {\n    const map = {};\n    for (const s of strs) {\n        const key = s.split('').sort().join('');\n        map[key] = map[key] || [];\n        map[key].push(s);\n    }\n    return Object.values(map);\n}",
     "diagram": "Input: ['eat', 'tea', 'tan', 'ate', 'nat', 'bat']\nKey 'aet' -> ['eat', 'tea', 'ate']\nKey 'ant' -> ['tan', 'nat']\nKey 'abt' -> ['bat']",
     "star": "E-commerce product catalog deduplication. Clustered scraped vendor titles that only differed in word order.",
     "metrics": "Cleaned up 1.2M duplicate product listings, saving 35% database index storage."},

    {"cat": "01-arrays-and-hashing", "id": 5, "lc": 347, "title": "Top K Frequent Elements", "diff": "Medium",
     "hinglish": "Array me se k sabse zyada aane wale elements nikalne hain. Bucket sort se O(N) me bina sorting ke solve karo.",
     "analogy": "Counting votes where buckets represent vote counts, reading from highest bucket down.",
     "brute": "HashMap frequency count + sort by count. Time: O(N log N), Space: O(N).",
     "optimal": "Bucket sort where bucket index represents frequency count. Time: O(N), Space: O(N).",
     "py": "def topKFrequent(nums, k):\n    count = {}\n    for n in nums: count[n] = count.get(n, 0) + 1\n    buckets = [[] for _ in range(len(nums) + 1)]\n    for n, c in count.items(): buckets[c].append(n)\n    res = []\n    for i in range(len(buckets)-1, 0, -1):\n        for n in buckets[i]:\n            res.append(n)\n            if len(res) == k: return res",
     "js": "function topKFrequent(nums, k) {\n    const count = new Map();\n    for (const n of nums) count.set(n, (count.get(n) || 0) + 1);\n    const buckets = Array.from({length: nums.length + 1}, () => []);\n    for (const [n, c] of count) buckets[c].push(n);\n    const res = [];\n    for (let i = buckets.length - 1; i > 0 && res.length < k; i--) {\n        if (buckets[i].length) res.push(...buckets[i]);\n    }\n    return res.slice(0, k);\n}",
     "diagram": "nums=[1,1,1,2,2,3], k=2\nCounts: {1:3, 2:2, 3:1}\nBuckets: [3: [1], 2: [2], 1: [3]] -> Output: [1, 2]",
     "star": "Real-time trending hashtag generation on a high-throughput event live stream.",
     "metrics": "Processed 15k events/sec with sub-10ms response time on trending dashboard widgets."},

    {"cat": "01-arrays-and-hashing", "id": 6, "lc": 238, "title": "Product of Array Except Self", "diff": "Medium",
     "hinglish": "Har index par baaki sabhi numbers ka product chahiye bina division operator use kiye. Prefix product aur Postfix product multiply karo.",
     "analogy": "Calculating your net balance without looking at your own transaction by multiplying previous transactions with future transactions.",
     "brute": "Nested loop multiplying all other items for each index. Time: O(N^2), Space: O(1).",
     "optimal": "Compute prefix products in first pass, multiply with postfix products in reverse pass. Time: O(N), Space: O(1) auxiliary.",
     "py": "def productExceptSelf(nums):\n    res = [1] * len(nums)\n    prefix = 1\n    for i in range(len(nums)):\n        res[i] = prefix\n        prefix *= nums[i]\n    postfix = 1\n    for i in range(len(nums)-1, -1, -1):\n        res[i] *= postfix\n        postfix *= nums[i]\n    return res",
     "js": "function productExceptSelf(nums) {\n    const res = new Array(nums.length).fill(1);\n    let prefix = 1;\n    for (let i = 0; i < nums.length; i++) {\n        res[i] = prefix;\n        prefix *= nums[i];\n    }\n    let postfix = 1;\n    for (let i = nums.length - 1; i >= 0; i--) {\n        res[i] *= postfix;\n        postfix *= nums[i];\n    }\n    return res;\n}",
     "diagram": "nums =   [1,  2,  3,  4]\nPrefix:  [1,  1,  2,  6]\nPostfix: [24, 12, 4,  1]\nResult:  [24, 12, 8,  6]",
     "star": "Financial portfolio risk analysis engine avoiding floating point division-by-zero errors when calculating variance weights.",
     "metrics": "Prevented division-by-zero crashes on 500k real-time asset evaluations."},

    {"cat": "01-arrays-and-hashing", "id": 7, "lc": 128, "title": "Longest Consecutive Sequence", "diff": "Medium",
     "hinglish": "Unsorted numbers me se sabse lambi lagataar chalne wali ginti ka length chahiye O(N) me. Set me daal kar check karo agar n-1 nahi hai toh n sequence ka start hai.",
     "analogy": "Finding the longest continuous domino chain on a table by only building from head pieces.",
     "brute": "Sort array and count longest contiguous run. Time: O(N log N), Space: O(1).",
     "optimal": "Store in HashSet. If (n - 1) not in set, it's a streak start; count up while (n + length) in set. Time: O(N), Space: O(N).",
     "py": "def longestConsecutive(nums):\n    num_set = set(nums)\n    longest = 0\n    for n in num_set:\n        if n - 1 not in num_set:\n            length = 1\n            while n + length in num_set: length += 1\n            longest = max(longest, length)\n    return longest",
     "js": "function longestConsecutive(nums) {\n    const set = new Set(nums);\n    let longest = 0;\n    for (const n of set) {\n        if (!set.has(n - 1)) {\n            let len = 1;\n            while (set.has(n + len)) len++;\n            longest = Math.max(longest, len);\n        }\n    }\n    return longest;\n}",
     "diagram": "[100, 4, 200, 1, 3, 2]\nStarts: 100 (len 1), 200 (len 1), 1 (1->2->3->4 len 4) -> Max = 4",
     "star": "User engagement gamification service calculating unbroken daily login streaks from epoch date integers.",
     "metrics": "Computed streak rewards for 4M daily active users in 3.1 seconds."},

    {"cat": "01-arrays-and-hashing", "id": 8, "lc": 271, "title": "Encode and Decode Strings", "diff": "Medium",
     "hinglish": "Strings ki list ko single string me encode karna hai aur wapas decode karna hai. Delimiter me length prefix use karte hain (jaise '4#lint').",
     "analogy": "Packing luggage where every parcel has a tag stating its exact byte length before content starts.",
     "brute": "Join with comma (breaks if strings contain commas).",
     "optimal": "Length prefix encoding: f'{len(s)}#{s}'. Time: O(N), Space: O(1).",
     "py": "def encode(strs):\n    return ''.join(f'{len(s)}#{s}' for s in strs)\ndef decode(s):\n    res, i = [], 0\n    while i < len(s):\n        j = s.find('#', i)\n        length = int(s[i:j])\n        res.append(s[j+1 : j+1+length])\n        i = j + 1 + length\n    return res",
     "js": "function encode(strs) {\n    return strs.map(s => `${s.length}#${s}`).join('');\n}\nfunction decode(s) {\n    const res = [];\n    let i = 0;\n    while (i < s.length) {\n        const hashIdx = s.indexOf('#', i);\n        const len = parseInt(s.slice(i, hashIdx));\n        res.push(s.slice(hashIdx + 1, hashIdx + 1 + len));\n        i = hashIdx + 1 + len;\n    }\n    return res;\n}",
     "diagram": "['lint', 'co#de'] -> '4#lint5#co#de' -> Decoded correctly preserving '#'",
     "star": "Custom binary RPC protocol handling user-generated text containing emoji and control delimiters.",
     "metrics": "Zero parsing errors across 100M+ payloads; 40% bandwidth savings compared to JSON."},

    # 02-Two Pointers (9-11)
    {"cat": "02-two-pointers", "id": 9, "lc": 125, "title": "Valid Palindrome", "diff": "Easy",
     "hinglish": "String ko aage aur piche se padhne par same lagna chahiye. Non-alphanumeric hatao aur do pointers (left aur right) se compare karo.",
     "analogy": "Inspecting a mirrored sign from both ends towards the center simultaneously.",
     "brute": "Reverse entire cleaned string and check equality. Time: O(N), Space: O(N).",
     "optimal": "Two pointers (left=0, right=len-1) skipping non-alphanumerics in-place. Time: O(N), Space: O(1).",
     "py": "def isPalindrome(s: str) -> bool:\n    l, r = 0, len(s) - 1\n    while l < r:\n        while l < r and not s[l].isalnum(): l += 1\n        while l < r and not s[r].isalnum(): r -= 1\n        if s[l].lower() != s[r].lower(): return False\n        l, r = l + 1, r - 1\n    return True",
     "js": "function isPalindrome(s) {\n    let l = 0, r = s.length - 1;\n    while (l < r) {\n        while (l < r && !/[a-zA-Z0-9]/.test(s[l])) l++;\n        while (l < r && !/[a-zA-Z0-9]/.test(s[r])) r--;\n        if (s[l].toLowerCase() !== s[r].toLowerCase()) return false;\n        l++; r--;\n    }\n    return true;\n}",
     "diagram": "'A man, a plan, a canal: Panama'\nL='a', R='a' -> match\nL='m', R='m' -> match -> Valid palindrome!",
     "star": "Data quality validation pipeline checking symmetric ISBN and serial voucher barcodes.",
     "metrics": "Eliminated string memory allocations, speeding up batch data ingestion by 4x."},

    {"cat": "02-two-pointers", "id": 10, "lc": 15, "title": "3Sum", "diff": "Medium",
     "hinglish": "Teen numbers jinka sum 0 ho. Array sort karo, ek number fix karo aur baaki do par Two Pointers lagao.",
     "analogy": "Forming a 3-person team where the first member is fixed, and the remaining two are selected from both ends.",
     "brute": "Three nested loops checking all triplets. Time: O(N^3), Space: O(1).",
     "optimal": "Sort array, loop i from 0 to N-2, use two pointers for remaining range. Skip duplicates. Time: O(N^2), Space: O(1) or O(N).",
     "py": "def threeSum(nums):\n    nums.sort()\n    res = []\n    for i in range(len(nums) - 2):\n        if i > 0 and nums[i] == nums[i-1]: continue\n        l, r = i + 1, len(nums) - 1\n        while l < r:\n            total = nums[i] + nums[l] + nums[r]\n            if total < 0: l += 1\n            elif total > 0: r -= 1\n            else:\n                res.append([nums[i], nums[l], nums[r]])\n                while l < r and nums[l] == nums[l+1]: l += 1\n                while l < r and nums[r] == nums[r-1]: r -= 1\n                l += 1; r -= 1\n    return res",
     "js": "function threeSum(nums) {\n    nums.sort((a, b) => a - b);\n    const res = [];\n    for (let i = 0; i < nums.length - 2; i++) {\n        if (i > 0 && nums[i] === nums[i - 1]) continue;\n        let l = i + 1, r = nums.length - 1;\n        while (l < r) {\n            const sum = nums[i] + nums[l] + nums[r];\n            if (sum < 0) l++;\n            else if (sum > 0) r--;\n            else {\n                res.push([nums[i], nums[l], nums[r]]);\n                while (l < r && nums[l] === nums[l + 1]) l++;\n                while (l < r && nums[r] === nums[r - 1]) r--;\n                l++; r--;\n            }\n        }\n    }\n    return res;\n}",
     "diagram": "nums=[-1, 0, 1, 2, -1, -4] -> Sorted: [-4, -1, -1, 0, 1, 2]\ni=-1, l=-1, r=2: sum = 0 -> [-1, -1, 2]\ni=-1, l=0, r=1: sum = 0 -> [-1, 0, 1]",
     "star": "Financial arbitrage scanner detecting zero-risk 3-currency triangular currency cycles.",
     "metrics": "Processed 10,000 FX pairs under 15ms avoiding quadratic explosion."},

    {"cat": "02-two-pointers", "id": 11, "lc": 11, "title": "Container With Most Water", "diff": "Medium",
     "hinglish": "Do vertical deewaron ke beech sabse zyada paani kitna aa sakta hai. Chhoti deewar ko aage badhao kyunki wahi height ko limit kar rahi hai.",
     "analogy": "Holding water between two rulers of different heights. Width decreases as you move in, so always move the shorter ruler.",
     "brute": "Check area between all pairs of vertical lines. Time: O(N^2), Space: O(1).",
     "optimal": "Two pointers at edges. Calculate area = min(h[l], h[r]) * (r - l). Move pointer with smaller height. Time: O(N), Space: O(1).",
     "py": "def maxArea(height):\n    l, r, max_w = 0, len(height) - 1, 0\n    while l < r:\n        area = min(height[l], height[r]) * (r - l)\n        max_w = max(max_w, area)\n        if height[l] < height[r]: l += 1\n        else: r -= 1\n    return max_w",
     "js": "function maxArea(height) {\n    let l = 0, r = height.length - 1, maxW = 0;\n    while (l < r) {\n        const area = Math.min(height[l], height[r]) * (r - l);\n        maxW = Math.max(maxW, area);\n        if (height[l] < height[r]) l++;\n        else r--;\n    }\n    return maxW;\n}",
     "diagram": "Heights: [1,8,6,2,5,4,8,3,7]\nL=0 (h=1), R=8 (h=7): Area = 1 * 8 = 8. Move L!\nL=1 (h=8), R=8 (h=7): Area = 7 * 7 = 49 (Max)!",
     "star": "Logistics parcel packing simulator optimizing rectangular container capacity for uneven warehouse shipments.",
     "metrics": "Optimized container packing throughput from O(N^2) to O(N) linear time for 200,000 package manifests."},

    # 03-Sliding Window (12-15)
    {"cat": "03-sliding-window", "id": 12, "lc": 121, "title": "Best Time to Buy and Sell Stock", "diff": "Easy",
     "hinglish": "Stock saste me kharidna hai aur mehenge me bechna hai. Minimum price track karte chalo aur har din maximum profit calculate karo.",
     "analogy": "Tracking the lowest purchase price you ever saw in history and calculating your profit if you sold today.",
     "brute": "Nested loops checking every buy and sell day pair. Time: O(N^2), Space: O(1).",
     "optimal": "Single pass tracking min_price and max_profit. Time: O(N), Space: O(1).",
     "py": "def maxProfit(prices):\n    min_p, max_p = float('inf'), 0\n    for p in prices:\n        min_p = min(min_p, p)\n        max_p = max(max_p, p - min_p)\n    return max_p",
     "js": "function maxProfit(prices) {\n    let minP = Infinity, maxP = 0;\n    for (const p of prices) {\n        minP = Math.min(minP, p);\n        maxP = Math.max(maxP, p - minP);\n    }\n    return maxP;\n}",
     "diagram": "[7, 1, 5, 3, 6, 4]\nMin so far: 7 -> 1 -> 1 -> 1 -> 1\nProfits: 0, 0, (5-1)=4, (3-1)=2, (6-1)=5 (Max) -> Result = 5",
     "star": "Crypto automated algorithmic trading bot identifying historical dip opportunities.",
     "metrics": "Executed in sub-millisecond O(N) streaming fashion over 1,000,000 tick prices."},

    {"cat": "03-sliding-window", "id": 13, "lc": 3, "title": "Longest Substring Without Repeating Characters", "diff": "Medium",
     "hinglish": "Bina kisi duplicate character ke sabse lambi substring ka length chahiye. Sliding window + Set ya Map use karo.",
     "analogy": "A camera aperture window that expands right until a duplicate is spotted, then contracts from left until duplicate is expelled.",
     "brute": "Check all substrings for duplicates. Time: O(N^3) or O(N^2), Space: O(min(N, M)).",
     "optimal": "Sliding window with Set/Map. Right pointer expands, Left pointer shrinks window on duplicate. Time: O(N), Space: O(min(N, M)).",
     "py": "def lengthOfLongestSubstring(s: str) -> int:\n    char_set = set()\n    l, max_len = 0, 0\n    for r in range(len(s)):\n        while s[r] in char_set:\n            char_set.remove(s[l]); l += 1\n        char_set.add(s[r])\n        max_len = max(max_len, r - l + 1)\n    return max_len",
     "js": "function lengthOfLongestSubstring(s) {\n    const set = new Set();\n    let l = 0, maxLen = 0;\n    for (let r = 0; r < s.length; r++) {\n        while (set.has(s[r])) {\n            set.delete(s[l]);\n            l++;\n        }\n        set.add(s[r]);\n        maxLen = Math.max(maxLen, r - l + 1);\n    }\n    return maxLen;\n}",
     "diagram": "'abcabcbb'\n[a] -> [ab] -> [abc] (len 3)\nNext 'a' -> Shrink window: [bca] -> [cab] -> [abc] -> Max Len = 3",
     "star": "Network packet inspection engine detecting unique header token sequences without repetition.",
     "metrics": "Processed streaming packet buffers in single-pass linear time without memory spikes."},

    {"cat": "03-sliding-window", "id": 14, "lc": 424, "title": "Longest Repeating Character Replacement", "diff": "Medium",
     "hinglish": "K characters ko kisi bhi character se replace kar sakte hain. Window me majority character count track karo.",
     "analogy": "A party where you can bring k non-themed guests into a themed photo window of size W.",
     "brute": "Check all substrings and their character replacements. Time: O(26 * N^2).",
     "optimal": "Sliding window. Window valid if `(window_len - max_freq) <= k`. Time: O(N), Space: O(1).",
     "py": "def characterReplacement(s: str, k: int) -> int:\n    count = {}\n    max_f, l, max_len = 0, 0, 0\n    for r in range(len(s)):\n        count[s[r]] = count.get(s[r], 0) + 1\n        max_f = max(max_f, count[s[r]])\n        while (r - l + 1) - max_f > k:\n            count[s[l]] -= 1\n            l += 1\n        max_len = max(max_len, r - l + 1)\n    return max_len",
     "js": "function characterReplacement(s, k) {\n    const count = {};\n    let maxF = 0, l = 0, maxLen = 0;\n    for (let r = 0; r < s.length; r++) {\n        count[s[r]] = (count[s[r]] || 0) + 1;\n        maxF = Math.max(maxF, count[s[r]]);\n        while ((r - l + 1) - maxF > k) {\n            count[s[l]]--;\n            l++;\n        }\n        maxLen = Math.max(maxLen, r - l + 1);\n    }\n    return maxLen;\n}",
     "diagram": "s = 'AABABBA', k = 1\nWindow [AABA] has three 'A' and one 'B'. (4 - 3) = 1 <= k (Valid, len 4)!",
     "star": "Telecom signal burst error correction system allowing k bits of noisy channel distortion.",
     "metrics": "Improved signal reconstruction speed by 10x using linear sliding window checks."},

    {"cat": "03-sliding-window", "id": 15, "lc": 76, "title": "Minimum Window Substring", "diff": "Hard",
     "hinglish": "String s me sabse chhota window dhundna hai jisme string t ke saare characters mojud hon.",
     "analogy": "Highlighting the shortest excerpt in a book that contains all target keywords.",
     "brute": "Generate all substrings and check if they contain all chars of t. Time: O(N^2 * M).",
     "optimal": "Two pointers window. Expand right until valid, contract left while valid to minimize window. Time: O(N + M), Space: O(N + M).",
     "py": "def minWindow(s: str, t: str) -> str:\n    if not t or not s: return ''\n    from collections import Counter\n    t_count = Counter(t)\n    window = {}\n    have, need = 0, len(t_count)\n    res, res_len = [-1, -1], float('inf')\n    l = 0\n    for r in range(len(s)):\n        c = s[r]\n        window[c] = window.get(c, 0) + 1\n        if c in t_count and window[c] == t_count[c]: have += 1\n        while have == need:\n            if (r - l + 1) < res_len:\n                res = [l, r]; res_len = r - l + 1\n            window[s[l]] -= 1\n            if s[l] in t_count and window[s[l]] < t_count[s[l]]: have -= 1\n            l += 1\n    return s[res[0]:res[1]+1] if res_len != float('inf') else ''",
     "js": "function minWindow(s, t) {\n    if (!s || !t) return '';\n    const tCount = {};\n    for (const c of t) tCount[c] = (tCount[c] || 0) + 1;\n    const window = {};\n    let have = 0, need = Object.keys(tCount).length;\n    let res = [-1, -1], resLen = Infinity, l = 0;\n    for (let r = 0; r < s.length; r++) {\n        const c = s[r];\n        window[c] = (window[c] || 0) + 1;\n        if (tCount[c] && window[c] === tCount[c]) have++;\n        while (have === need) {\n            if ((r - l + 1) < resLen) { res = [l, r]; resLen = r - l + 1; }\n            window[s[l]]--;\n            if (tCount[s[l]] && window[s[l]] < tCount[s[l]]) have--;\n            l++;\n        }\n    }\n    return resLen === Infinity ? '' : s.slice(res[0], res[1] + 1);\n}",
     "diagram": "s='ADOBECODEBANC', t='ABC'\nFirst match: 'ADOBEC' (len 6)\nMinimized final match: 'BANC' (len 4) 🎉",
     "star": "Text search highlighting engine returning the most compact snippet containing all search keywords.",
     "metrics": "Delivered snippet search in O(N) under 5ms on multi-megabyte customer support transcripts."},

    # 04-Stack (16)
    {"cat": "04-stack", "id": 16, "lc": 20, "title": "Valid Parentheses", "diff": "Easy",
     "hinglish": "Brackets sahi order me open aur close hone chahiye. Stack me push karo, closing bracket aane par top element match karo.",
     "analogy": "Stack of cafeteria trays. Last bracket placed on the stack must be the first one taken off and matched.",
     "brute": "Repeatedly replace '()', '[]', '{}' with '' until no changes (O(N^2)).",
     "optimal": "Stack based single pass. Push open brackets, pop and match for closing. Time: O(N), Space: O(N).",
     "py": "def isValid(s: str) -> bool:\n    stack = []\n    mapping = {')': '(', '}': '{', ']': '['}\n    for c in s:\n        if c in mapping:\n            if not stack or stack[-1] != mapping[c]: return False\n            stack.pop()\n        else: stack.append(c)\n    return not stack",
     "js": "function isValid(s) {\n    const stack = [];\n    const map = { ')': '(', '}': '{', ']': '[' };\n    for (const c of s) {\n        if (map[c]) {\n            if (stack.pop() !== map[c]) return false;\n        } else stack.push(c);\n    }\n    return stack.length === 0;\n}",
     "diagram": "s = '([{}])'\nStack: [ ( ] -> [ (, [ ] -> [ (, [, { ] -> pop { -> pop [ -> pop ( -> Empty Stack = Valid!",
     "star": "Custom JSON and AST expression parser for a low-code workflow rule evaluator.",
     "metrics": "Detected syntax errors at parse-time instantly with zero false-positives."},

    # 05-Binary Search (17-18)
    {"cat": "05-binary-search", "id": 17, "lc": 153, "title": "Find Minimum in Rotated Sorted Array", "diff": "Medium",
     "hinglish": "Sorted array ko kisi pivot par rotate kiya gaya hai. O(log N) me minimum nikalna hai binary search se.",
     "analogy": "Finding where a sorted phone directory was split and glued back together.",
     "brute": "Linear scan finding the smallest value. Time: O(N), Space: O(1).",
     "optimal": "Binary search. If nums[mid] > nums[right], minimum lies in right half; else left half. Time: O(log N), Space: O(1).",
     "py": "def findMin(nums):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] > nums[r]: l = mid + 1\n        else: r = mid\n    return nums[l]",
     "js": "function findMin(nums) {\n    let l = 0, r = nums.length - 1;\n    while (l < r) {\n        const mid = Math.floor((l + r) / 2);\n        if (nums[mid] > nums[r]) l = mid + 1;\n        else r = mid;\n    }\n    return nums[l];\n}",
     "diagram": "[4, 5, 6, 7, 0, 1, 2]\nMid = 7 > Right = 2 -> Search right half: [0, 1, 2] -> Min = 0",
     "star": "Distributed log timestamp index lookup on circularly rotated server partition files.",
     "metrics": "Reduced partition offset resolution from 200ms to 0.4ms."},

    {"cat": "05-binary-search", "id": 18, "lc": 33, "title": "Search in Rotated Sorted Array", "diff": "Medium",
     "hinglish": "Rotated array me target element search karna hai. Har step par pata karo ki kaunsa half normally sorted hai.",
     "analogy": "Searching for a house number on a circular street with a split checkpoint.",
     "brute": "Linear search. Time: O(N), Space: O(1).",
     "optimal": "Modified Binary Search. Check if left or right half is sorted, then decide if target falls inside. Time: O(log N), Space: O(1).",
     "py": "def search(nums, target):\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        if nums[l] <= nums[mid]: # Left sorted\n            if nums[l] <= target < nums[mid]: r = mid - 1\n            else: l = mid + 1\n        else: # Right sorted\n            if nums[mid] < target <= nums[r]: l = mid + 1\n            else: r = mid - 1\n    return -1",
     "js": "function search(nums, target) {\n    let l = 0, r = nums.length - 1;\n    while (l <= r) {\n        const mid = Math.floor((l + r) / 2);\n        if (nums[mid] === target) return mid;\n        if (nums[l] <= nums[mid]) {\n            if (nums[l] <= target && target < nums[mid]) r = mid - 1;\n            else l = mid + 1;\n        } else {\n            if (nums[mid] < target && target <= nums[r]) l = mid + 1;\n            else r = mid - 1;\n        }\n    }\n    return -1;\n}",
     "diagram": "[4, 5, 6, 7, 0, 1, 2], target = 0\nMid=7. Left half [4..7] is sorted, target is NOT in [4..7]. Search right half!\nTarget 0 found at index 4.",
     "star": "Inverted distributed database index partition search under sharded rolling storage.",
     "metrics": "Maintained sub-1ms point-lookup SLA over 10M record segment indices."}
]

print(f"Loaded {len(BLIND_75_DATA)} core Blind 75 problem models.")
